### Dockerfile
# Use an official Python runtime as a parent image
FROM python:3.13-slim

# Set the working directory to /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt ./

RUN pip install --trusted-host pypi.python.org -r requirements.txt

COPY . .


# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
#ENV NAME World

# Run app.py when the container launches
#CMD ["gunicorn", "-c", "gunicorn.py", "run:app"]
